[global]
   workgroup = WORKGROUP
   server string = Samba Server
   netbios name = debianA
   security = user
   map to guest = Bad User

[share]
   path = /srv/samba/share
   browsable =yes
   writable = yes
   guest ok = yes
   read only = no
